name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: Raibo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: raibo-461721

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy raibo-ai \
          --source . \
          --region asia-southeast1 \
          --platform managed \
          --allow-unauthenticated
